kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: demo-2-route
  namespace: demo-2
  labels:
    gateway: external-http
spec:
  hostnames:
  - "demo-2.runk8s.dev"
  parentRefs:
  - name: bravo-team-external-http
    namespace: team-bravo-tenant
  rules:
  - backendRefs:
    - group: net.gke.io
      kind: ServiceImport
      name: whereami
      port: 80