apiVersion: v1
data:
  token: Z2l0aHViX3BhdF8xMUFCSFZYVEEweUtMVnp2ZFpTRDl4X3AwRnA1b04xSFpqUlNNWDhEbFZ3Ym9qV0NpQVNUc0JIZ29iU096WnZGbEFMTFg3U0pDTk5ha3lIZHJX
kind: Secret
metadata:
  creationTimestamp: null
  name: github-token
  namespace: flux-system
